# Generated by Django 3.1.3 on 2020-11-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-publish',), 'verbose_name': 'note', 'verbose_name_plural': 'notes'},
        ),
    ]
