# Generated by Django 3.1.3 on 2020-11-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_note_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='author',
        ),
    ]
